# development:
#   adapter: async

# test:
#   adapter: test

# production:
#   adapter: redis
#   url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
#   channel_prefix: exchange_rate_production

redis: &redis
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>

production: *redis  
development: *redis
test:
  adapter: async